print("What kind of music do bubbles hate")
input()
print("POP")
print("-------------------------------------------")
print("Time for another joke!!!")
input()
print("Why shouldn’t you trust atoms?")
input()
print("Because they make up everything!!!")
print("------------------------------------------")
print("Time for another joke!!!")
input()
print("Why are ghost bad liars??")
input()
print("Because they are see-through!!")
print("------------------------------------------")
print("Time for another joke!!!")
input()
print("Why are astronauts so clean??")
input()
print("Because they take meteor showers!!")
User_like=input("Did you enjoy hearing my jokes? y/n")
if User_like:('y')
print("Im so happy you enjoys my jokes!")

print("You are mean")
    