print("Hello would you like to hear a story? if so press enter")
input()
print("Im going to ask you questions if order for you to fill in the blanks")
user_animal=input("Pick an animal:")
setting=input("choose a setting:")
user_food=input("Choose a food:")
user_friend=input("Name a character:")
print("Press enter to hear your story!!!")
input()
print(f"Today a {user_animal} goes to a restaurant to eat {user_food} with their best friend {user_friend}.")
print("The end!!!!!!!!")
str(print("if you would like to give me feedback press enter"))
input()
user_opinion=input("Did you like the story I made??? y/n ")
if user_opinion=="y":
    print("Im so glad you enjoyed it!")
else:
   print("Im sorry you didn't like my sorry")
print("Thank you for your time")
print("If you would like to see a message press enter!!!")
input()
print(r" ___________.__                   __           ._.")
print(r" \__    ___/|  |__ _____    ____ |  | __  _____| |")
print(r"   |    |   |  |  \\__  \  /    \|  |/ / /  ___/ |")
print(r"   |    |   |   Y  \/ __ \|   |  \    <  \___ \ \|")
print(r"   |____|   |___|  (____  /___|  /__|_ \/____  >__")
print(r"                 \/     \/     \/     \/     \/ \/")
print("--------------------------------------------------------------")
print("Hello would you like to hear another story? if so press enter")
input()
print("Im going to ask you questions if order for you to fill in the blanks")
user_plant=input("Pick an plant:")
atmosphere=input("choose a atmosphere:")
place=input("Choose a place: ")
user_weapon=input("Choose a weapon:")
user_friend2=input("Name a character:")
print("Press enter to hear your story!!!")
input()
print(f"Dangerous {user_plant}'s live in {place}.Your job is to fight them off using {user_weapon} with your best friend {user_friend2}.")
print("The end!!!!!!!!")
print("If you would like to see another message press enter!!!")
input()
print(r"_____.___.  _____ _____.___._._.")
print(r"\__  |   | /  _  \\__  |   | | |")
print(r" /   |   |/  /_\  \/   |   | | |")
print(r" \____   /    |    \____   |\|\|")
print(r" / ______\____|__  / ______|____")
print(r" \/              \/\/       \/\/")
input()
print("-----------------------------------------------------------------------")
print(r"  _____________________________________________________________")
print(r" /   _____/\_   _____/\_   ___ \______   \_   _____/\__    ___/")
print(r"  \_____  \  |    __)_ /    \  \/|       _/|    __)_   |    |  ")
print(r"  /        \ |        \\     \___|    |   \|        \  |    |  ")
print(r" /_______  //_______  / \______  /____|_  /_______  /  |____|  ")
print(r"         \/         \/         \/       \/        \/         ")
